### ISSUE TITLE
meteor tools

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#116]
Guys

I tested your meteor tools branch and you display an error in cosole showing following:

```
W20151107-10:40:10.974(11)? (STDERR) Error: source map test
W20151107-10:40:10.974(11)? (STDERR)     at Object.<anonymous> (C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\src\main_server.js:18:15)
W20151107-10:40:10.974(11)? (STDERR)     at __webpack_require__ (C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\webpack\bootstrap 6fd7d2ac1ccf26a4aa2c:19:1)
W20151107-10:40:10.975(11)? (STDERR)     at Object.<anonymous> (C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\webpack\bootstrap 6fd7d2ac1ccf26a4aa2c:39:1)
W20151107-10:40:10.975(11)? (STDERR)     at __webpack_require__ (C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\webpack\bootstrap 6fd7d2ac1ccf26a4aa2c:19:1)
W20151107-10:40:10.975(11)? (STDERR)     at C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\webpack\bootstrap 6fd7d2ac1ccf26a4aa2c:39:1
W20151107-10:40:10.975(11)? (STDERR)     at C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\webpack\bootstrap 6fd7d2ac1ccf26a4aa2c:39:1
W20151107-10:40:10.975(11)? (STDERR)     at C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\app\server\assets\webpack:\C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\dist\fixtures.js:19:8
W20151107-10:40:10.975(11)? (STDERR)     at C:\Users\Tomas\Documents\Projects\meteor-webpack-react-master\meteor\.meteor\local\build\programs\server\boot.js:242:10
W20151107-10:40:10.975(11)? (STDERR)     at Array.forEach (native)
W20151107-10:40:10.976(11)? (STDERR)     at Function._.each._.forEach (C:\Users\Tomas\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
```

what does this represent? 

also, what is the advantage of using this branch?

**Comment by jedwards1211** [comment]
The point of that error is to see if source maps have been applied to its stack trace.  As you can see in the first line of the stack trace, the source loc `main_server.js:18:15`, which means the source maps are working properly (otherwise you'd see something 1000s of lines into the webpack bundle).

The two main advantages of that branch are:
* It will continue to receive updates to my `webpack-meteor-tools` package
* It's the only branch where node source-map-support is currently used correctly, without breaking Meteor global variables.

**Comment by gaurav-** [comment]
There's an actual error thrown after the source map console log…
```
W20151109-12:20:18.839(5.5)? (STDERR) /Users/gaurav/repos/meteor-webpack-react/webpack/assets/server.bundle.js:1
W20151109-12:20:18.839(5.5)? (STDERR) var require = Npm.require;
W20151109-12:20:18.839(5.5)? (STDERR)               ^
W20151109-12:20:18.839(5.5)? (STDERR) ReferenceError: Npm is not defined
W20151109-12:20:18.839(5.5)? (STDERR)     at Object.<anonymous> (/Users/gaurav/repos/meteor-webpack-react/webpack/assets/server.bundle.js:1:15)
W20151109-12:20:18.840(5.5)? (STDERR)     at Module._compile (module.js:456:26)
W20151109-12:20:18.840(5.5)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151109-12:20:18.840(5.5)? (STDERR)     at Module.load (module.js:356:32)
W20151109-12:20:18.840(5.5)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151109-12:20:18.840(5.5)? (STDERR)     at Module.require (module.js:364:17)
W20151109-12:20:18.840(5.5)? (STDERR)     at require (module.js:380:17)
W20151109-12:20:18.840(5.5)? (STDERR)     at Object.Npm.require (/Users/gaurav/repos/meteor-webpack-react/meteor_core/.meteor/local/build/programs/server/boot.js:150:18)
W20151109-12:20:18.840(5.5)? (STDERR)     at /Users/gaurav/repos/meteor-webpack-react/meteor_core/.meteor/local/build/programs/server/app/server/meteor:/💻app/server/require.server.bundle.js:3:1
W20151109-12:20:18.840(5.5)? (STDERR)     at /Users/gaurav/repos/meteor-webpack-react/meteor_core/.meteor/local/build/programs/server/app/server/require.server.bundle.js:4:4
```
Seems the [smoke test](https://github.com/jedwards1211/meteor-webpack-react/blob/webpack-meteor-tools/app/main_server.js#L14) doesn't help catch this as it gets executed much later in the final server bundle.

**Comment by tomitrescak** [comment]
Huh, I just tried to move my project to meteor tools branch and I also received 'npm is not defined error'. I'm not sure how to get rid of it. Any idea?

**Comment by tomitrescak** [comment]
Nevermind ... it was a forgotten .js file from the master branch that was messing up the build. Cleaning the meteor_core directory and adding only custom files has helped.

I know you @jedwards1211 are very busy, but would be grrrreat if you could do a new build with this branch, or even merge it with master. But, I understand how busy it can get ...
