### ISSUE TITLE
[ERROR] Cannot find Cannot find module 'temp' , core-js-no-number when running dev

### ISSUE THREAD

**Issue by anhhh11** [jedwards1211/meteor-webpack-react#143]
I clone lastest meteor-webpack-react(0.0.1) then install then run command as following and have gotten errors:
E:\meteor-webpack-react>node ./dev.js
Building core-js@2.4.0 without ES6 number constructor...
module.js:339
    throw err;
    ^

Error: Cannot find module 'temp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\meteor-webpack-react\node_modules\core-js\build\index.js:9:10)
    at Object.<anonymous> (E:\meteor-webpack-react\node_modules\core-js\build\index.js:104:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
Build completed in 13.529s

Hash: 5742307b365a9c681948
Version: webpack 1.13.0
Time: 13507ms
               Asset    Size  Chunks             Chunk Names
    server.bundle.js  767 kB       0  [emitted]  main
server.bundle.js.map  843 kB       0  [emitted]  main
chunk    {0} server.bundle.js, server.bundle.js.map (main) 686 kB [rendered]

ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/core-js-no-number in E:\meteor-webpack-react\webpack
 @ multi main

**Comment by afrantz** [comment]
Same error for me.

**Comment by Mokto** [comment]
I think you have to use npm@3.
