### ISSUE TITLE
weird issues with underscore after update to latest master

### ISSUE THREAD

**Issue by randomnerd** [jedwards1211/meteor-webpack-react#97]
```
W20151011-15:38:23.033(3)? (STDERR) /Users/randomnerd/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79
W20151011-15:38:23.033(3)? (STDERR)       obj.forEach(iterator, context);
W20151011-15:38:23.033(3)? (STDERR)           ^
W20151011-15:38:23.034(3)? (STDERR) TypeError: undefined is not a function
W20151011-15:38:23.034(3)? (STDERR)     at /Users/randomnerd/Sites/bx/meteor_core/.meteor/local/build/programs/server/app/server/server.bundle.js:1:-26
W20151011-15:38:23.034(3)? (STDERR)     at /Users/randomnerd/Sites/bx/meteor_core/.meteor/local/build/programs/server/app/server/server.bundle.js:5836:4
W20151011-15:38:23.034(3)? (STDERR)     at /Users/randomnerd/Sites/bx/meteor_core/.meteor/local/build/programs/server/boot.js:242:10
W20151011-15:38:23.034(3)? (STDERR)     at Array.forEach (native)
W20151011-15:38:23.035(3)? (STDERR)     at Function._.each._.forEach (/Users/randomnerd/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151011-15:38:23.035(3)? (STDERR)     at /Users/randomnerd/Sites/bx/meteor_core/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 1
```
this is happening even with empty main_server.js... any ideas?

**Comment by randomnerd** [comment]
somehow got this resolved resetting meteor_core to HEAD and then copying my files over again.
